POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###
POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "BigManSquare",
    "email" : "bigbigman@gmail.com",
    "password" : "realbigman"
}

###
POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "RemuRimeSlime",
    "email" : "rurime@gmail.com",
    "password" : "slimetime"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll

//testing for the authorizationRoutes
//test for Remu
###
POST http://localhost:8081/auth/assignAuth
Content-Type: application/json

{
    "userID" : "65e0d6d5923c6fb9837fe209",
    "authorizationRole" : "Admin"
}

//testing fail case
###
POST http://localhost:8081/auth/assignAuth
Content-Type: application/json

{
    "userID" : "65e0d6d5923c6fb9837fe003",
    "authorizationRole" : "Admin"
}

//test for BigMan
###
POST http://localhost:8081/auth/assignAuth
Content-Type: application/json

{
    "userID" : "65e0d3ae923c6fb9837fe1f9",
    "authorizationRole" : "User"
}

//test for robbert
###
POST http://localhost:8081/auth/assignAuth
Content-Type: application/json

{
    "userID" : "65fc6c850fc37441469227e7",
    "authorizationRole" : "Admin"
}

###
GET http://localhost:8081/auth/getAllAuth
Content-Type: application/json

###
GET http://localhost:8081/auth/getAuthByID
Content-Type: application/json

{
    "userID" : "65e0d6d5923c6fb9837fe209"
}

###
GET http://localhost:8081/auth/getAuthByID
Content-Type: application/json

{
    "userID" : "65e0d3ae923c6fb9837fe1f9"
}

//testing a failed request
###
GET http://localhost:8081/auth/getAuthByID
Content-Type: application/json

{
    "userID" : "65e0d3ae923c6fb9837fe22g5"
}

###
GET http://localhost:8081/auth/allUnderAuth
Content-Type: application/json

{
    "authorizationRole" : "User"
}

//deletes authorization for BigManSquare
###
POST http://localhost:8081/auth/deleteAuth
Content-Type: application/json

{
    "userID" : "65e0d3ae923c6fb9837fe1f9"
}


//testing for the shopping cart routes
###
POST http://localhost:8081/cart/createCart
Content-Type: application/json

{
    "username" : "new",
    "userID" : "1"
}

//testing for getTickets
###
GET http://localhost:8081/cart/getTickets
Content-Type: application/json

{
    "userID" : "1"
}

//testing for clearCart, reduceCart, increaseCart and deleteCarts
###
POST http://localhost:8081/cart/clearCart
Content-Type: application/json

{
    "userID" : "1"
}

###
POST http://localhost:8081/cart/reduceCart
Content-Type: application/json

{
    "username" : "new",
    "userID" : "1"
}

###
POST http://localhost:8081/cart/increaseCart
Content-Type: application/json

{
    "username" : "new",
    "userID" : "1"
}

###
POST http://localhost:8081/cart/tempIncrease
Content-Type: application/json

{
    "username" : "new",
    "userID" : "1"
}

###
POST http://localhost:8081/cart/deleteCarts
Content-Type:  application/json

###
GET  http://localhost:8081/MBTAuser/getUserID
Content-Type: application/json 

{
    "userID" : "65fc6c850fc37441469227e7"
}

###
GET  http://localhost:8081/MBTAuser/getUsername

Content-Type: application/json 

{
    "username" : "Robert Swifflebottom"
}

###
POST http://localhost:8081/MBTAuser/ticketUsage
Content-Type: application/json 

{
    "userID" : "65fc6c850fc37441469227e7"
}

###
DELETE http://localhost:8081/MBTAuser/deleteUsedTickets
Content-Type: application/json 

{
    "userID" : "65fc6c850fc37441469227e7"
}
