POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###
POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "BigManSquare",
    "email" : "bigbigman@gmail.com",
    "password" : "realbigman"
}

###
POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "RemuRimeSlime",
    "email" : "rurime@gmail.com",
    "password" : "slimetime"
}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8080/user/deleteAll

//testing for the authorizationRoutes
//test for Remu
###
POST http://localhost:8081/auth/assignAuth
Content-Type: application/json

{
    "userID" : "66030412fb3f77975f646508",
    "username" : "RemuRimeSlime",
    "authorizationRole" : "Admin"
}

//testing fail case (wrong ID, right username)
###
POST http://localhost:8081/auth/assignAuth
Content-Type: application/json

{
    "userID" : "65e0d6d5923c6fb9837fe003",
    "username" : "Kobati",
    "authorizationRole" : "Admin"
}

//testing failcase (wrong ID, right username)
###
POST http://localhost:8081/auth/assignAuth
Content-Type: application/json

{
    "userID" : "661313d8fb3f77963f646562",
    "username" : "BigManSquare",
    "authorizationRole" : "User"
}

//test for BigMan
###
POST http://localhost:8081/auth/assignAuth
Content-Type: application/json

{
    "userID" : "660303d8fb3f77975f646504",
    "username" : "BigManSquare",
    "authorizationRole" : "User"
}

//test for robbert
###
POST http://localhost:8081/auth/assignAuth
Content-Type: application/json

{
    "userID" : "65fc6c850fc37441469227e7",
    "username" : "Robert Swifflebottom",
    "authorizationRole" : "User"
}

###
GET http://localhost:8081/auth/getAllAuth
Content-Type: application/json

//get auth of Remu
###
GET http://localhost:8081/auth/getAuthByID
Content-Type: application/json

{
    "userID" : "66030412fb3f77975f646508"
}

//get auth of BigMan
###
GET http://localhost:8081/auth/getAuthByID
Content-Type: application/json

{
    "userID" : "660303d8fb3f77975f646504"
}

//testing a failed request
###
GET http://localhost:8081/auth/getAuthByID
Content-Type: application/json

{
    "userID" : "65e0d3ae923c6fb9837fe22g5"
}

###
GET http://localhost:8081/auth/allUnderAuth
Content-Type: application/json

{
    "authorizationRole" : "User"
}

//deletes authorization for BigManSquare
###
POST http://localhost:8081/auth/deleteAuth
Content-Type: application/json

{
    "userID" : "660303d8fb3f77975f646504"
}

//deletes authorization for the fail cases (if they somehow get through)
//Kobati
###
POST http://localhost:8081/auth/deleteAuth
Content-Type: application/json

{
    "userID" : "65e0d6d5923c6fb9837fe003"
}

//BigManSquare
###
POST http://localhost:8081/auth/deleteAuth
Content-Type: application/json

{
    "userID" : "661313d8fb3f77963f646562"
}


//testing for creating a shopping cart
###
POST http://localhost:8081/cart/createCart
Content-Type: application/json

{
    "username" : "new"
}

//testing for get methods

###
GET http://localhost:8081/cart/getCart/seanpotter045@gmail.com
Content-Type: application/json

###
GET http://localhost:8081/cart/getOneWay/66174a7d204238cacfa18140
Content-Type: application/json

###
GET http://localhost:8081/cart/getWeekendPass/66174a7d204238cacfa18140
Content-Type: application/json


//testing for clearCart, reduce/increase, and deleteCarts
###
POST http://localhost:8081/cart/clearCart
Content-Type: application/json

{
    "userID" : "1"
}

###
POST http://localhost:8081/cart/reduceOW
Content-Type: application/json

{
    "userID" : "1"
}

###
POST http://localhost:8081/cart/reduceOW
Content-Type: application/json

{
    "userID" : "660c3114af2e532e9aa95090"
}

###
POST http://localhost:8081/cart/reduceWP
Content-Type: application/json

{
    "userID" : "1"
}

###
POST http://localhost:8081/cart/increaseOW
Content-Type: application/json

{
    "userID" : "66174a7d204238cacfa18140"
}

###
POST http://localhost:8081/cart/increaseWP
Content-Type: application/json

{
    "userID" : "66174a7d204238cacfa18140"
}

###
POST http://localhost:8081/cart/deleteCarts
Content-Type:  application/json

###
GET  http://localhost:8081/MBTAuser/getUserID
Content-Type: application/json 

{
    "userID" : "65fc6c850fc37441469227e7"
}

###
GET  http://localhost:8081/MBTAuser/getUsername

Content-Type: application/json 

{
    "username" : "Robert Swifflebottom"
}

###
POST http://localhost:8081/MBTAuser/ticketUsage
Content-Type: application/json 

{
    "userID" : "65fc6c850fc37441469227e7"
}

###
DELETE http://localhost:8081/MBTAuser/deleteUsedTickets
Content-Type: application/json 

{
    "userID" : "65fc6c850fc37441469227e7"
}
